### ISSUE TITLE
No auto-completion

### ISSUE THREAD

**Issue by chupins** [DaelonSuzuka/nicegui-vscode#1]
Hi, 

When I'm typing, i'm having an overlay of the classes info but nothing is proposed to complete what i'm writing : 
![autocompletion](https://github.com/user-attachments/assets/1497b15c-48d9-4332-bdd7-a9c933c0d7ea)

**Comment by DaelonSuzuka** [comment]
What happens when you hit ctrl + space?

**Comment by chupins** [comment]
Oh my bad, I didn't know I have to do it.
It works perfectly !

**Comment by DaelonSuzuka** [comment]
@chupins You actually don't *need* to do that every time, I just wanted to figure out of it the entire extension was broken or not. 

There's a VSCode setting that controls whether suggestions will be automatically show up while typing, and by default that is disabled when your cursor is inside of a string or comment.

<details>
<summary>Quick Suggestions Settings</summary>

![image](https://github.com/user-attachments/assets/913613dc-c2d6-4918-9d80-58ab7dd1be10)

</details>

But I just published version `0.6.0` that automatically changes that setting for you!
